const STORE="budget_foyer_v4_clean";
const PAGES=["dashboard","import","transactions","categories","settings"];
const TITLES={dashboard:["Dashboard","Vue globale du foyer"],import:["Import CSV","Ajoute tes relevés"],transactions:["Transactions","Classe les opérations"],categories:["Catégories","Règles automatiques"],settings:["Réglages","Données locales"]};
const CATS=["Courses","Essence","Maison","Électricité / Gaz","Eau","Internet / Téléphone","Assurances","Crédit / Loyer","Santé","Enfants","Loisirs","Restaurants","Abonnements","Impôts","Vêtements","Achats divers","Revenus","Épargne","Retraits espèces","Virements internes","Frais bancaires","Auto","Non catégorisé"];
const DEFAULT_RULES=[["CARREFOUR","Courses"],["LECLERC","Courses"],["INTERMARCHE","Courses"],["LIDL","Courses"],["ALDI","Courses"],["AUCHAN","Courses"],["SUPER U","Courses"],["TOTAL","Essence"],["ESSO","Essence"],["AVIA","Essence"],["CARBURANT","Essence"],["EDF","Électricité / Gaz"],["ENGIE","Électricité / Gaz"],["ORANGE","Internet / Téléphone"],["FREE","Internet / Téléphone"],["SFR","Internet / Téléphone"],["BOUYGUES","Internet / Téléphone"],["AXA","Assurances"],["MAIF","Assurances"],["MACIF","Assurances"],["ASSURANCE","Assurances"],["LOYER","Crédit / Loyer"],["PRET","Crédit / Loyer"],["PHARMACIE","Santé"],["MEDECIN","Santé"],["AMAZON","Achats divers"],["PAYPAL","Achats divers"],["NETFLIX","Abonnements"],["SPOTIFY","Abonnements"],["APPLE.COM","Abonnements"],["RESTAURANT","Restaurants"],["MCDONALD","Restaurants"],["IMPOT","Impôts"],["DGFIP","Impôts"],["SALAIRE","Revenus"],["CAF","Revenus"],["CPAM","Revenus"],["RETRAIT","Retraits espèces"],["DAB","Retraits espèces"],["FRAIS","Frais bancaires"],["NORAUTO","Auto"],["FEU VERT","Auto"]].map(([keyword,category])=>({keyword,category}));
let state=load(), active="dashboard";
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{tx:[],rules:DEFAULT_RULES,period:24}}catch(e){return{tx:[],rules:DEFAULT_RULES,period:24}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function norm(s){return String(s??"").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’']/g," ").replace(/\s+/g," ").trim()}
function money(n){return (n||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}
function amount(v){let s=String(v??"").trim();if(!s)return 0;s=s.replace(/\u00A0/g," ").replace(/€/g,"").replace(/\s/g,"");let neg=false;if(/^\(.*\)$/.test(s)){neg=true;s=s.slice(1,-1)}if(s.endsWith("-")){neg=true;s=s.slice(0,-1)}if(s.startsWith("-")){neg=true;s=s.slice(1)}s=s.replace(/\./g,"").replace(",",".");let n=Number(s);return Number.isFinite(n)?(neg?-Math.abs(n):n):0}
function dateParse(v){let s=String(v??"").trim();let m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);if(m){let y=m[3].length==2?"20"+m[3]:m[3];return `${y}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`}m=s.match(/^(\d{4})[\/.-](\d{1,2})[\/.-](\d{1,2})$/);if(m)return`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;let d=new Date(s);return isNaN(d)?null:d.toISOString().slice(0,10)}
function delimiter(text){let sample=text.split(/\r?\n/).filter(Boolean).slice(0,10).join("\n");return [";","\t",","].map(d=>[d,(sample.match(new RegExp(d=="\t"?"\\t":"\\"+d,"g"))||[]).length]).sort((a,b)=>b[1]-a[1])[0][0]}
function split(line,d){let out=[],cur="",q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c=='"'){if(q&&line[i+1]=='"'){cur+='"';i++}else q=!q}else if(c==d&&!q){out.push(cur.trim().replace(/^"|"$/g,""));cur=""}else cur+=c}out.push(cur.trim().replace(/^"|"$/g,""));return out}
function headerScore(cols){let j=norm(cols.join(" ")),score=0;["DATE","LIBELLE","OPERATION","DEBIT","CREDIT","MONTANT","VALEUR"].forEach(k=>{if(j.includes(k))score+=3});return score+Math.min(cols.length,8)}
function findHeader(lines,d){let best={i:0,h:split(lines[0]||"",d),s:-1};lines.slice(0,20).forEach((l,i)=>{let h=split(l,d),s=headerScore(h);if(s>best.s)best={i,h,s}});return best}
function col(headers, words){let hs=headers.map(norm);for(let group of words){let ws=group.map(norm);let exact=hs.findIndex(h=>ws.includes(h));if(exact>=0)return exact;let partial=hs.findIndex(h=>ws.some(w=>h.includes(w)||w.includes(h)));if(partial>=0)return partial}return -1}
function parseCSV(text){
 text=text.replace(/^\uFEFF/,"");let d=delimiter(text);let lines=text.split(/\r?\n/).filter(l=>l.trim());if(!lines.length)throw Error("Fichier vide");
 let hi=findHeader(lines,d), h=hi.h;
 let dateI=col(h,[["DATE OPERATION","DATE D OPERATION","DATE DE L OPERATION","DATE"],["DATE COMPTABLE"],["DATE VALEUR"]]);
 let libI=col(h,[["LIBELLE","LIBELLE OPERATION","LIBELLE DE L OPERATION"],["DESCRIPTION","DESIGNATION","INTITULE"],["OPERATION","NATURE"]]);
 let debitI=col(h,[["DEBIT EUROS","DEBIT EURO","DEBIT"],["MONTANT DEBIT","SORTIE","DEPENSE"]]);
 let creditI=col(h,[["CREDIT EUROS","CREDIT EURO","CREDIT"],["MONTANT CREDIT","ENTREE","RECETTE"]]);
 let montantI=col(h,[["MONTANT EUROS","MONTANT EURO","MONTANT"],["AMOUNT","VALEUR"]]);
 let debug=`Séparateur détecté : ${d=="\t"?"tabulation":d}\nLigne entête : ${hi.i+1}\nColonnes détectées :\n${h.map((x,i)=>`${i}: ${x}`).join("\n")}\n\nIndex date=${dateI}, libellé=${libI}, débit=${debitI}, crédit=${creditI}, montant=${montantI}`;
 if(dateI<0||libI<0||(debitI<0&&creditI<0&&montantI<0)){let e=Error("Colonnes non reconnues. Ouvre Diagnostic CSV et envoie-moi les colonnes affichées.");e.debug=debug;throw e}
 let rows=[];
 for(let line of lines.slice(hi.i+1)){let c=split(line,d);let dt=dateParse(c[dateI]), label=c[libI];if(!dt||!label)continue;let deb=0,cre=0;if(debitI>=0)deb=Math.abs(amount(c[debitI]));if(creditI>=0)cre=Math.abs(amount(c[creditI]));if(montantI>=0&&debitI<0&&creditI<0){let m=amount(c[montantI]);if(m<0)deb=Math.abs(m);else cre=m}if(!deb&&!cre)continue;rows.push({id:"",date:dt,label,clean:cleanLabel(label),debit:deb,credit:cre,cat:"",account:""})}
 if(!rows.length){let e=Error("Colonnes trouvées mais aucune opération lisible.");e.debug=debug;throw e}
 rows.debug=debug;return rows
}
function cleanLabel(s){return String(s).replace(/\b(CB|CARTE|PAIEMENT|PRELEVEMENT|PRLV|SEPA|ACHAT|FACTURE)\b/gi," ").replace(/\d{2}[\/.-]\d{2}[\/.-]\d{2,4}/g," ").replace(/\s+/g," ").trim()}
function id(t){let raw=[t.date,norm(t.label),t.debit.toFixed(2),t.credit.toFixed(2),t.account].join("|"),h=0;for(let i=0;i<raw.length;i++)h=((h<<5)-h)+raw.charCodeAt(i)|0;return"t"+Math.abs(h)}
function cat(t){if(t.credit&&!t.debit)return"Revenus";let hay=norm(t.label+" "+t.clean);let r=state.rules.find(r=>hay.includes(norm(r.keyword)));return r?r.category:"Non catégorisé"}
function periodRows(){let rows=[...state.tx].sort((a,b)=>b.date.localeCompare(a.date));if(state.period>=999)return rows;let max=rows.reduce((m,t)=>t.date>m?t.date:m,"");if(!max)return[];let d=new Date(max);d.setMonth(d.getMonth()-state.period+1);d.setDate(1);let min=d.toISOString().slice(0,10);return rows.filter(t=>t.date>=min)}
function months(rows){return[...new Set(rows.map(t=>t.date.slice(0,7)))].sort()}
function switchPage(p,dir=0){if(p==active)return;let old=$(`.page[data-page="${active}"]`), neu=$(`.page[data-page="${p}"]`);if(old){old.classList.remove("active");old.classList.add(dir<0?"exit-left":"exit-right");setTimeout(()=>old.classList.remove("exit-left","exit-right"),360)}neu.classList.add("active");active=p;$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.page==p));$("#title").textContent=TITLES[p][0];$("#subtitle").textContent=TITLES[p][1];requestAnimationFrame(render)}
function render(){fill();dash();txList();rules();$("#period").value=state.period}
function fill(){let accounts=[...new Set(state.tx.map(t=>t.account))];$("#accountFilter").innerHTML='<option value="">Comptes</option>'+accounts.map(a=>`<option>${a}</option>`).join("");$("#catFilter").innerHTML='<option value="">Catégories</option>'+CATS.map(c=>`<option>${c}</option>`).join("");$("#ruleCat").innerHTML=CATS.map(c=>`<option>${c}</option>`).join("")}
function dash(){let r=periodRows(), ms=months(r), mc=Math.max(ms.length,1), exp=r.reduce((s,t)=>s+t.debit,0), inc=r.reduce((s,t)=>s+t.credit,0);$("#kpiExpenses").textContent=money(exp);$("#kpiIncome").textContent=money(inc);$("#kpiBalance").textContent=money((inc-exp)/mc);$("#kpiExpensesAvg").textContent=money(exp/mc)+"/mois";$("#kpiIncomeAvg").textContent=money(inc/mc)+"/mois";$("#kpiCount").textContent=r.length;$("#kpiMonths").textContent=ms.length+" mois";let by={};r.filter(t=>t.debit).forEach(t=>{by[t.cat]??={sum:0,n:0};by[t.cat].sum+=t.debit;by[t.cat].n++});let arr=Object.entries(by).map(([k,v])=>({k,avg:v.sum/mc,sum:v.sum})).sort((a,b)=>b.sum-a.sum).slice(0,8),max=Math.max(...arr.map(x=>x.avg),1);$("#topCats").innerHTML=arr.map(x=>`<div><div class="bar-meta"><b>${x.k}</b><span>${money(x.avg)}</span></div><div class="bar-bg"><div class="bar-fill" style="width:${Math.round(x.avg/max*100)}%"></div></div></div>`).join("")||'<p style="color:#6b7280;margin:0">Aucune dépense.</p>';chart(r)}
function chart(rows){let c=$("#chart"),ctx=c.getContext("2d"),rect=c.getBoundingClientRect(),s=devicePixelRatio||1,w=Math.max(280,rect.width),h=Math.max(100,rect.height);c.width=w*s;c.height=h*s;ctx.setTransform(s,0,0,s,0,0);ctx.clearRect(0,0,w,h);let ms=months(rows),data=ms.map(m=>{let rr=rows.filter(t=>t.date.slice(0,7)==m);return{m,exp:rr.reduce((a,t)=>a+t.debit,0),inc:rr.reduce((a,t)=>a+t.credit,0)}});ctx.font="12px -apple-system";if(!data.length){ctx.fillStyle="#6b7280";ctx.fillText("Importe un CSV pour afficher le graphique.",14,32);return}let max=Math.max(...data.map(d=>Math.max(d.exp,d.inc)),1),pad=24,gap=5,bw=Math.max(5,(w-pad*2)/data.length-gap),base=h-20;ctx.strokeStyle="#e5e7eb";ctx.beginPath();ctx.moveTo(pad,base);ctx.lineTo(w-pad,base);ctx.stroke();data.forEach((d,i)=>{let x=pad+i*(bw+gap),eh=d.exp/max*(h-48),ih=d.inc/max*(h-48);ctx.fillStyle="#111827";ctx.fillRect(x,base-eh,bw/2,eh);ctx.fillStyle="#9ca3af";ctx.fillRect(x+bw/2,base-ih,bw/2,ih)})}
function txList(){let r=periodRows(),q=norm($("#search").value),a=$("#accountFilter").value,c=$("#catFilter").value;if(q)r=r.filter(t=>norm(t.label+" "+t.cat).includes(q));if(a)r=r.filter(t=>t.account==a);if(c)r=r.filter(t=>t.cat==c);$("#txCount").textContent=r.length+" opération"+(r.length>1?"s":"");$("#txList").innerHTML=r.slice(0,1000).map(t=>`<div class="tx"><div><b>${t.clean||t.label}</b><br><small>${new Date(t.date).toLocaleDateString("fr-FR")} · ${t.account}</small></div><div class="amount ${t.debit?'neg':'pos'}">${money(t.debit||t.credit)}</div><select data-id="${t.id}">${CATS.map(c=>`<option ${c==t.cat?"selected":""}>${c}</option>`).join("")}</select></div>`).join("")||'<p style="color:#6b7280">Aucune transaction.</p>'}
function rules(){$("#rules").innerHTML=state.rules.map((r,i)=>`<span class="chip"><b>${r.keyword}</b> → ${r.category}<button data-rule="${i}">×</button></span>`).join("")}
$$(".tab").forEach(b=>b.onclick=()=>switchPage(b.dataset.page,PAGES.indexOf(b.dataset.page)-PAGES.indexOf(active)));
$("#period").onchange=e=>{state.period=+e.target.value;save();render()};["search","accountFilter","catFilter"].forEach(id=>$("#"+id).oninput=txList);
$("#file").onchange=async e=>{let files=[...e.target.files],added=0,skip=0,errs=[],dbg="";for(let f of files){try{let text=await f.text(),rows=parseCSV(text);dbg=rows.debug||"";let existing=new Set(state.tx.map(t=>t.id));rows.forEach(t=>{t.account=$("#account").value;t.cat=cat(t);t.id=id(t);if(existing.has(t.id))skip++;else{state.tx.push(t);existing.add(t.id);added++}})}catch(err){errs.push(`${f.name}: ${err.message}`);dbg=err.debug||dbg||""}}save();render();let m=$("#importMessage");m.style.display="block";m.className="message"+(errs.length?" error":"");m.textContent=`${added} opération(s) ajoutée(s), ${skip} doublon(s).`+(errs.length?" "+errs.join(" | "):" Import OK.");$("#debugText").textContent=dbg||"Aucun diagnostic.";$("#debugBox").style.display=dbg?"block":"none";e.target.value=""}
$("#txList").onchange=e=>{if(e.target.matches("select[data-id]")){let t=state.tx.find(x=>x.id==e.target.dataset.id);if(t){t.cat=e.target.value;save();dash()}}}
$("#addRule").onclick=()=>{let k=$("#ruleKey").value.trim().toUpperCase(),c=$("#ruleCat").value;if(k.length<2)return;state.rules.unshift({keyword:k,category:c});$("#ruleKey").value="";save();render()}
$("#rules").onclick=e=>{if(e.target.dataset.rule!==undefined){state.rules.splice(+e.target.dataset.rule,1);save();render()}}
$("#recat").onclick=()=>{state.tx.forEach(t=>t.cat=cat(t));save();render()}
$("#wipe").onclick=()=>{if(confirm("Tout effacer ?")){localStorage.removeItem(STORE);state=load();render()}}
$("#export").onclick=()=>{let rows=periodRows(),csv=["Date;Compte;Libellé;Catégorie;Débit euros;Crédit euros"].concat(rows.map(t=>[t.date,t.account,`"${t.label.replaceAll('"','""')}"`,t.cat,String(t.debit).replace(".",","),String(t.credit).replace(".",",")].join(";"))).join("\n");let blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="budget-foyer.csv";a.click();URL.revokeObjectURL(a.href)}
let sx=0,sy=0,cx=0,drag=false;$("#pages").ontouchstart=e=>{if(e.target.closest("input,select,button,.tx-list,.bars,.chips,.drop"))return;sx=cx=e.touches[0].clientX;sy=e.touches[0].clientY;drag=true};$("#pages").ontouchmove=e=>{if(!drag)return;cx=e.touches[0].clientX;let dx=cx-sx,dy=e.touches[0].clientY-sy;if(Math.abs(dx)>Math.abs(dy)*1.4&&Math.abs(dx)>12){$(".page.active").style.setProperty("--drag-x",Math.max(-38,Math.min(38,dx*.18))+"px")}};$("#pages").ontouchend=e=>{if(!drag)return;drag=false;let dx=cx-sx,p=$(".page.active");p.style.setProperty("--drag-x","0px");if(Math.abs(dx)>82){let i=PAGES.indexOf(active),ni=dx<0?i+1:i-1;if(ni>=0&&ni<PAGES.length)switchPage(PAGES[ni],dx<0?1:-1)}}
window.onresize=()=>requestAnimationFrame(()=>chart(periodRows()));
render();
